mongoConfiguration:
                    host:     dbh44.mongolab.com
                    port:     27447
                    user:     trinity-cms
                    password: tr1n1ty
                    db:       trinity